# -*- coding: utf-8 -*-
"""
전략 기본 설정 (DB에 없을 때 사용)

config.yaml의 strategies 섹션을 제거하고, DB 기반으로 전환했습니다.
이 모듈은 DB에 전략이 없을 때 사용할 기본값을 정의합니다.
마이그레이션: scripts/seed_strategy_settings.py 로 config.yaml → DB 이관 가능
"""

# 전략별 기본 config (DB row 없을 때 사용)
STRATEGY_DEFAULTS = {
    "ema_cross": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "30m",
        "htf_timeframes": ["4h", "1d"],
        "score_threshold": 0.7,
        "atr_multiplier": 1.5,
        "use_rsi_filter": False,
        "use_vwap_filter": False,
    },
    "ict": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "15m",
        "ob_lookback": 20,
        "fvg_min_gap_pct": 0.001,
        "min_confidence": 0.65,
        "min_risk_reward": 1.5,
        "atr_multiplier": 2.0,
        "proximity_pct": 0.01,
        "use_volume_filter": True,
        "use_rsi_filter": True,
        "volume_multiplier": 1.3,
        "rsi_overbought": 70,
        "rsi_oversold": 30,
        "keltner_multiplier": 2.5,
    },
    "rsi": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "1h",
        "overbought": 70,
        "oversold": 30,
        "use_trend_filter": True,
        "rsi_period": 14,
        "atr_multiplier": 1.5,
        "min_confidence": 0.5,
    },
    "bollinger": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "15m",
        "period": 20,
        "std_dev": 3,
        "mode": "breakout",
        "volume_filter": True,
        "atr_multiplier": 1.5,
        "min_confidence": 0.5,
        "use_ma_cross": True,
    },
    "keltner_ict_turtle": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "1h",
        "ema_period": 20,
        "atr_period": 20,
        "keltner_multiplier": 2.5,
        "donchian_period": 55,
        "ob_lookback": 10,
        "fvg_min_gap": 0.001,
        "volume_multiplier": 1.3,
        "require_ict": False,
        "min_confidence": 0.5,
        "atr_multiplier": 2.5,
    },
    "pattern_rag": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "1h",
        "ollama_url": "http://localhost:11434",
        "ollama_model": "qwen2.5:7b-instruct",
        "top_k": 10,
        "min_confidence": 0.6,
        "min_patterns": 5,
        "min_avg_return": 3,
        "auto_learn": True,
        "learn_on_no_patterns": True,
        "atr_multiplier": 2,
    },
    "ema_divergence_volume": {
        "enabled": True,
        "use_ai": False,
        "timeframe": "15m",
        "ema_fast": 20,
        "ema_slow": 59,
        "divergence_lookback": 5,
        "min_spread_increase_pct": 0.05,
        "volume_ma_period": 20,
        "volume_multiplier": 1.5,
        "atr_multiplier": 1.5,
    },
    "bb_adaptive_rsi": {
        "enabled": True,
        "use_ai": True,
        "timeframe": "15m",
        "bb_length": 20,
        "bb_std_dev": 3,
        "er_length": 10,
        "fast_rsi_length": 2,
        "slow_rsi_length": 30,
        "rsi_smooth": 3,
        "rsi_overbought": 70,
        "rsi_oversold": 30,
        "use_rsi_filter": True,
        "atr_multiplier": 1.5,
        "min_confidence": 0.5,
    },
}
